# NOTICE: This file is written with the assumption that it will be used in parca-dev/cross-builder.
# - There are paths in this file that are specific to parca-dev/cross-builder and Github Actions.
# - Unfortunately, Goreleaser does not support templating environment variables per build config.
project_name: parca-agent
dist: ./goreleaser/dist
env:
  - CGO_ENABLED=1
  - LDFLAGS=-fuse-ld=lld
  - CC=zig cc
  - CC_VERSION=$(zig version)
before:
  hooks:
    - go mod tidy
    - make ARCH=amd64 libbpf
    - make ARCH=amd64 bpf
    - make clean-3rdparty-libraries
    - make ARCH=arm64 libbpf
    - make ARCH=arm64 bpf
builds:
  # NOTICE: This build config assumes that the build runs on a x86_64 host.
  - main: ./cmd/parca-agent/
    id: "parca-agent-linux"
    binary: parca-agent
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    # https://goreleaser.com/customization/build/#reproducible-builds
    mod_timestamp: "{{ .CommitTimestamp }}"
    env:
      # Needed by CGO.
      - >-
        {{ if eq .Arch "amd64" }}CC=zig cc -target x86_64-linux-musl
        {{ else if eq .Arch "arm64" }}CC=zig cc -target aarch64-linux-musl
        {{ end }}
      - CGO_CFLAGS=-I/__w/parca-agent/parca-agent/dist/libbpf/{{.Arch}}/usr/include
      - CGO_LDFLAGS=-L/__w/parca-agent/parca-agent/dist/libz/{{.Arch}}/lib -L/__w/parca-agent/parca-agent/dist/libelf/{{.Arch}}/lib /__w/parca-agent/parca-agent/dist/libzstd/{{.Arch}}/lib/libzstd.a /__w/parca-agent/parca-agent/dist/libbpf/{{.Arch}}/libbpf.a PKG_CONFIG=''
      # Needed for compiling libbpf (defined in Make).
      - CFLAGS=-g -O2 -Werror -Wall -std=gnu89 -fpic -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer
    flags:
      - -mod=readonly
      - -buildmode=pie
      - -trimpath
      - -v
    ldflags:
      # https://goreleaser.com/customization/build/#reproducible-builds
      # {{.CommitDate}} is the date of the commit to make builds reproducible.
      - -X main.version={{.Version}} -X main.commit={{.FullCommit}} -X main.date={{.CommitDate}}
      - -X main.cc={{.Env.CC}} -X main.ccVersion={{.Env.CC_VERSION}}
      - -linkmode=external -extldflags=-static
    tags:
      - osusergo
      - netgo

archives:
  # e.g. parca_agent_0.15.0_Linux_aarch64.tar.gz, parca_agent_0.15.0_Linux_x86_64.tar.gz
  - name_template: >-
      {{ .ProjectName }}_
      {{- trimprefix .Version "v" }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
    format: binary
    format_overrides:
      - goos: windows
        format: zip
    files:
      - "LICENSE*"
      - "README*"
      - src: goreleaser/dist/async-profiler/LICENSE
        dst: async-profiler
        strip_parent: true
      - src: goreleaser/dist/async-profiler/x64/libc/*
        dst: async-profiler/x64/libc
        strip_parent: true
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Tag }}-{{ .ShortCommit }}"
release:
  prerelease: auto
  # Defaults to empty.
  footer: |
    ## Docker images

    `docker pull ghcr.io/parca-dev/parca-agent:{{ .Tag }}`

    ## Thanks!

    Join our [Discord server](https://discord.com/invite/ZgUpYgpzXy);
    Follow us on [Twitter](https://twitter.com/ParcaDev);
    Read the [documentation](https://www.parca.dev/docs/overview).
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
